spring:
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.138.125:8848

  application:
    name: gulimall-auth-server

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  redis:
    host: 192.168.77.130
    port: 6379

  session:
    store-type: redis

server:
  port: 8150
  servlet:
    session:
      timeout: 30m
