spring:
  datasource:
    username: root
    password: "root"
    url: jdbc:mysql://47.111.138.125:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.111.138.125:8848
    alicloud:
      access-key: LTAI4G4W1RA4JXz2QhoDwHhi                  #阿里云的access-key
      secret-key: R99lmDOJumF2x43ZBKT259Qpe70Oxw
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-hello                              #阿里云对象存储服务创建的桶
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5

  application:
    name: gulimall-third-party


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 30000

logging:
  level:
    com.example.gulimall.product: info